import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Posts
        </h1>

        <ul className={styles.posts}>
          <li>
            <p className={styles.postsContent}>I’m learning to design a new website by following a tutorial by Colby.</p>
            <p className={styles.postsDate}>02/08/2021</p>
          </li>
          <li>
            <p className={styles.postsContent}>I’m learning to design a new website by following a tutorial by Colby.</p>
            <p className={styles.postsDate}>02/08/2021</p>
          </li>
          <li>
            <p className={styles.postsContent}>I’m learning to design a new website by following a tutorial by Colby.</p>
            <p className={styles.postsDate}>02/08/2021</p>
          </li>
        </ul>

        <form>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formSubmit}>
            Add New Post
          </button>
        </form>

      </main>
    </div>
  )
}
